### PR TITLE
refactor(price-feeder): Move TickerPrice and CandlePrice to types package

### PR DESCRIPTION
**Pull request by zarazan**
The TickerPrice and CandlePrice types are used across the oracle package so they are being moved to the types package to cleanup the provider code 

- Move TickerPrice and CandlePrice to the types package
- Move the NewTickerPrice and NewCandlePrice functions to the type package
- Add tests for NewTickerPrice and NewCandlePrice

## Description

closes: https://github.com/umee-network/umee/issues/936

---

### Author Checklist

_All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues._

I have...

- [x] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [x] added `!` to the type prefix if API or client breaking change
- [x] added appropriate labels to the PR
- [x] targeted the correct branch (see [PR Targeting](https://github.com/umee-network/umee/blob/main/CONTRIBUTING.md#pr-targeting))
- [x] provided a link to the relevant issue or specification
- [x] added a changelog entry to `CHANGELOG.md`
- [x] included comments for [documenting Go code](https://blog.golang.org/godoc)
- [x] updated the relevant documentation or specification
- [x] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed

### Reviewers Checklist

_All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items._

I have...

- [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed state machine logic
- [ ] reviewed API design and naming
- [ ] reviewed documentation is accurate
- [ ] reviewed tests and test coverage
- [ ] manually tested (if applicable)

### CODE REVIEW

**Review by RafilxTenfen — APPROVED** [review]
utACK, Nice 
I would also want to give a name ( #1167 ) to the string key in maps like 
`AggregatedProviderCandles map[Name]map[string][]types.CandlePrice` 
`AggregatedProviderCandles map[Name]map[Asset][]types.CandlePrice`

But it can be done in another PR

**Review by adamewozniak — APPROVED** [review]
LGTM!

**Comment by adamewozniak** [comment]
> utACK, Nice 
> 
> I would also want to give a name ( #1167 ) to the string key in maps like 
> 
> `AggregatedProviderCandles map[Name]map[string][]types.CandlePrice` to -> `AggregatedProviderCandles map[Name]map[Asset][]types.CandlePrice`
> 
> 
> 
> But it can be done in another PR 

Agree 👍 @zarazan if there's not an issue open for that please open up a new one or use the existing tissue for it

**Comment by adamewozniak** [comment]
Hey @zarazan ! Please sign your commits and we'll be able to merge this in 🥳

**Comment by zarazan** [comment]
> utACK, Nice I would also want to give a name ( #1167 ) to the string key in maps like `AggregatedProviderCandles map[Name]map[string][]types.CandlePrice` to -> `AggregatedProviderCandles map[Name]map[Asset][]types.CandlePrice`
> 
> But it can be done in another PR

I'll open an issue for it. I started to add a name for the Asset as well, decided the "Name" one needs to be renamed and then saw how many files I'd have to touch. As a side note it seems like these named strings are a little more trouble than they are worth when used across packages due to all the changes that it requires when modifying them. Or just name things right the first time (heavy sarcasm) 😄

**Review by robert-zaremba — APPROVED** [review]
utACK

**Comment by robert-zaremba** [comment]
one note: we should rather limit what we put into the `types` package, it is an anti pattern really.

**Comment by zarazan** [comment]
> one note: we should rather limit what we put into the `types` package, it is an anti pattern really.

I totally agree, feels like the entire Oracle folder could have stayed as one package. It also doesn't help that the Cosmos SDK uses this anti pattern...

**Comment by robert-zaremba** [comment]
>  It also doesn't help that the Cosmos SDK uses this anti pattern...

We have been moving away from it in new modules.

**Pull request merged**
