### PR TITLE
fix: buf cosmos-sdk version

### PR DESCRIPTION
**Pull request by robert-zaremba**
## Description

Fixes _Failure: buf.build/cosmos/cosmos-sdk:af8d763f189a4482b59f9f283b446293: does not exist_
https://github.com/umee-network/umee/actions/runs/3066818251/jobs/4952419735

---

### Author Checklist

_All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues._

I have...

- [ ] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] added `!` to the type prefix if API or client breaking change
- [ ] added appropriate labels to the PR
- [ ] targeted the correct branch (see [PR Targeting](https://github.com/umee-network/umee/blob/main/CONTRIBUTING.md#pr-targeting))
- [ ] provided a link to the relevant issue or specification
- [ ] added a changelog entry to `CHANGELOG.md`
- [ ] included comments for [documenting Go code](https://blog.golang.org/godoc)
- [ ] updated the relevant documentation or specification
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed

### Reviewers Checklist

_All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items._

I have...

- [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed state machine logic
- [ ] reviewed API design and naming
- [ ] reviewed documentation is accurate
- [ ] reviewed tests and test coverage
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by RafilxTenfen** [comment]
it is failing after `make proto-gen`

**Comment by RafilxTenfen** [comment]
> it is failing after `make proto-gen`

Maybe we should test build after running proto in the CI

**Comment by robert-zaremba** [comment]
@RafilxTenfen you mean it is failing locally? on my localhost it works. CI is also passing (and we check proto there). Try to remove the container: `docker rm umee-proto-gen-v0.7`.

**Review by toteki — APPROVED** [review]

**Comment by toteki** [comment]
By the way, was it ok for me to merge this?

It will create the following diff in a few places on `make proto-gen` (see #1396)
```
-       _ "github.com/gogo/protobuf/gogoproto"
+       _ "github.com/cosmos/gogoproto/gogoproto"
```

**Comment by robert-zaremba** [comment]
@toteki , this PR should not be merged, I will try to revert it.

**Pull request merged**
