### PR TITLE
chore: add json for launching vscode Debugger in project

### PR DESCRIPTION
**Pull request by justyntemme**
## Description

Adds ability to use vscode as a debugger, and set breakpoints.

----

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

- [x] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [x] added `!` to the type prefix if API or client breaking change
- [x] targeted the correct branch (see [PR Targeting](https://github.com/umee-network/umee/blob/main/CONTRIBUTING.md#pr-targeting))
- [x] provided a link to the relevant issue or specification
- [ ] added a changelog entry to `CHANGELOG.md`
- [ ] included comments for [documenting Go code](https://blog.golang.org/godoc)
- [ ] updated the relevant documentation or specification
- [ ] reviewed "Files changed" and left comments if necessary
- [x] confirmed all CI checks have passed

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

- [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] confirmed `!` in the type prefix if API or client breaking change
- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed state machine logic
- [ ] reviewed API design and naming
- [ ] reviewed documentation is accurate
- [ ] reviewed tests and test coverage
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by toteki** [comment]
Is this necessary? I've been using VScode, including debugging, without a config file (default settings in other words)

**Comment by justyntemme** [comment]
@toteki I was not aware of how to launch debugging without the config. I don't think that's a misconfiguration on my end, but i could be wrong.

**Review by alexanderbez — CHANGES_REQUESTED** [review]
@justyntemme editors settings should be local to the developer. Let's not commit them to source control.

**Comment by justyntemme** [comment]
Sounds good, will close, thanks team!

**Pull request closed without merging**
