### PR TITLE
fix: temporarily disable new historacle proto

### PR DESCRIPTION
**Pull request by toteki**
## Description

First step of #1585 - second would be re-enabling.

I think this is a cleaner path to `v3.2.0` release than leaving `main` branch incompatible or building a migration to put the params in early.

### CODE REVIEW

**Comment by adamewozniak** [comment]
imo this is the cleaner way to go.
cc @zarazan @rbajollari

**Review by rbajollari — APPROVED** [review]

**Comment by adamewozniak** [comment]
@toteki after this PR is merged will we be g2g on the gravity bridge upgrade?

**Comment by toteki** [comment]
This and #1577 yeah

**Comment by robert-zaremba** [comment]
I'm going sleep now. Personally i think it's better to add the fix rather then doing 3 similar commits (old push, this revert, and the new re-push with fix). Of course this only make sense if we are not under big pressure.l, and i already have most of the gov message part done. Need to update CLI .

**Comment by robert-zaremba** [comment]
That being said I'm not against revert and redo if others support it.

**Review by robert-zaremba — CHANGES_REQUESTED** [review]
As noted in other comment, we don't need to go back and forth with these proto changes. So blocking it because these are unnecessary back-and-forth changes. 

I've prepared a migration: https://github.com/umee-network/umee/pull/1593
still need to test it.

The full migration to go out of the param space is a bit more complex, so will be better to do it in v3.3

**Pull request closed without merging**
