### PR TITLE
fix: Dragonberry patch

### PR DESCRIPTION
**Pull request by robert-zaremba**
## Description

Applying Dragonberry fix for v3.1.x

---

### Author Checklist

_All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues._

I have...

- [ ] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] added `!` to the type prefix if API or client breaking change
- [ ] added appropriate labels to the PR
- [ ] targeted the correct branch (see [PR Targeting](https://github.com/umee-network/umee/blob/main/CONTRIBUTING.md#pr-targeting))
- [ ] provided a link to the relevant issue or specification
- [ ] added a changelog entry to `CHANGELOG.md`
- [ ] included comments for [documenting Go code](https://blog.golang.org/godoc)
- [ ] updated the relevant documentation or specification
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed

### Reviewers Checklist

_All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items._

I have...

- [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed state machine logic
- [ ] reviewed API design and naming
- [ ] reviewed documentation is accurate
- [ ] reviewed tests and test coverage
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by toteki** [comment]
Check the build+test failures - we need to fix a few things

**Comment by toteki** [comment]
Could this be unintentionally picking up a few changes from `0.46.2` -> `0.46.3` that aren't dragonberry related?

**Review by RafilxTenfen — APPROVED** [review]
Not sure why we need `nodeservice` on this, maybe removed if is not strictly needed?

**Comment by robert-zaremba** [comment]
Extracted it to https://github.com/umee-network/umee/pull/1513 - once it will be merged, it will cancel in this PR.

**Comment by robert-zaremba** [comment]
Seams this PR must be merged first, I'm reverting the new query service PR.

**Comment by robert-zaremba** [comment]
> Could this be unintentionally picking up a few changes from `0.46.2` -> `0.46.3` that aren't dragonberry related?

I think that was related to price feeder missing the update. I've updated go.mod in price feeder and it worked afterwords.

**Pull request merged**
