### PR TITLE
refactor: remove proto getters

### PR DESCRIPTION
**Pull request by robert-zaremba**
## Description

closes: #1114

---

### Author Checklist

_All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues._

I have...

- [x] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] added `!` to the type prefix if API or client breaking change
- [x] added appropriate labels to the PR
- [x] targeted the correct branch (see [PR Targeting](https://github.com/umee-network/umee/blob/main/CONTRIBUTING.md#pr-targeting))
- [x] provided a link to the relevant issue or specification
- [ ] added a changelog entry to `CHANGELOG.md`
- [ ] included comments for [documenting Go code](https://blog.golang.org/godoc)
- [ ] updated the relevant documentation or specification
- [x] reviewed "Files changed" and left comments if necessary
- [x] confirmed all CI checks have passed

### Reviewers Checklist

_All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items._

I have...

- [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed state machine logic
- [ ] reviewed API design and naming
- [ ] reviewed documentation is accurate
- [ ] reviewed tests and test coverage
- [ ] manually tested (if applicable)

### CODE REVIEW

**Review by RafilxTenfen — APPROVED** [review]

**Comment by RafilxTenfen** [comment]
this needs to go to changelogs ?

**Review by toteki — APPROVED** [review]

**Comment by toteki** [comment]
No changelog needed in my opinion since observable behavior is unaffected - I'll go ahead and merge

**Comment by robert-zaremba** [comment]
I will add changelog update

**Comment by toteki** [comment]
I added labels and changed type prefix to `refactor` (I had to go back and read the guide since my first thought was `chore`)

**Comment by robert-zaremba** [comment]
> added labels

We don't need to add labels in PRs linked to issues. If PR is not linked to issue, then we can use it as a "task" by adding to a board - only then we need to add labels.

> changed type prefix to refactor

Thanks, makes sense.

**Pull request merged**
