### PR TITLE
[WIP] Added rbuilder to have reproducible builds

### PR DESCRIPTION
**Pull request by facundomedica**
This PR is aimed to solve https://github.com/umee-network/umee/issues/9

Locally I could only run it successfully with `linux/amd64`. Will try to run it with `linux/amd64 darwin/amd64 linux/arm64 darwin/arm64` when I have some more free time :) 

The github workflow still needs to be updated, I don't have any experience with that, maybe some other contributor can jump in and avoid me lots of trial and error 😆 .

### CODE REVIEW

**Comment by alexanderbez** [comment]
Thanks for the contribution @facundomedica! Happy to help with any workflow related issues. Also, there is an issue with macOS and Ledger https://github.com/tendermint/images/issues/70. I'd rather see that resolved first before we start using rbuilder.

**Comment by facundomedica** [comment]
@alexanderbez that's too bad! Seeing the response on the other issue, we might not want to use rbuilder at all? 😱

**Comment by alexanderbez** [comment]
@facundomedica that's OK. I think we should still proceed with this PR. If we can have a method that produces reproducible hashes, that's good.

**Comment by facundomedica** [comment]
@alexanderbez should we keep the darwin platform?

**Comment by facundomedica** [comment]
@alexanderbez Also rbuilder doesn't support `darwin/arm64`. 😞 

> TARGET_PLATFORMS - whitespace-separated list of operating system/architecture pairs. linux/amd64, linux/arm64, darwin/amd64, and windows/amd64 are supported. Default: linux/amd64.

**Comment by alexanderbez** [comment]
@facundomedica yes, we must support linux and macOS. I think we can skip `darwin/arm64` for now until rbuilder supports it.

**Comment by alessio** [comment]
> @alexanderbez Also rbuilder doesn't support `darwin/arm64`. 
> 
> > TARGET_PLATFORMS - whitespace-separated list of operating system/architecture pairs. linux/amd64, linux/arm64, darwin/amd64, and windows/amd64 are supported. Default: linux/amd64.

Hi there, `rbuilder`'s author speaking here. Have you tried to build for `darwin/arm64` anyway? When I left that message in the documentation probably `darwin/arm64` was not yet officially supported.

**Comment by facundomedica** [comment]
@alessio I've tried building for MacOS but got an issue with Go's linker or something like that, I couldn't find a solution to it.

```
$ make build-reproducible
latest-build
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
--> Cleaning...
Building for darwin/arm64
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
go build -mod=readonly -tags "netgo ledger" -ldflags '-X github.com/cosmos/cosmos-sdk/version.Name=umee -X github.com/cosmos/cosmos-sdk/version.AppName=umeed -X github.com/cosmos/cosmos-sdk/version.Version=use-rbuilder-051f4b320c25ff7bcbfc4ad40143289d0b9acab7 -X github.com/cosmos/cosmos-sdk/version.Commit=051f4b320c25ff7bcbfc4ad40143289d0b9acab7 -X "github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger" -X github.com/tendermint/tendermint/version.TMCoreSemVer=v0.34.11' -o /tmp/tmp.TeQ5TnXyjZ/buildsources/build/ ./...
# github.com/umee-network/umee/cmd/umeed
/usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/tmp/go-link-892326816/go.o: file not recognized: file format not recognized
collect2: error: ld returned 1 exit status

make: *** [Makefile:71: build] Error 2
make: *** [Makefile:78: build-reproducible] Error 2
```

**Comment by alexanderbez** [comment]
Thanks for the effort and contribution @facundomedica, but we're just going to stick with gorelease for our entire release pipeline, including reproducible build artifacts 👍

**Comment by alessio** [comment]
> file not recognized: file format not recognized

Setting CGO_ENABLED=1 explicitly should make this go away

**Pull request closed without merging**
