### PR TITLE
chore: Remove image publishing from main umee repo (moving)

### PR DESCRIPTION
**Pull request by dreamcodez**
Given how much the complexity of this has grown -- I don't think it really belongs in this repo anymore -- I need to refactor this in any case for our next testnet and I think its better if i move it to the infra repo.

----

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

- [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] confirmed `!` in the type prefix if API or client breaking change
- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed state machine logic
- [ ] reviewed API design and naming
- [ ] reviewed documentation is accurate
- [ ] reviewed tests and test coverage
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by toteki** [comment]
Is the failing image publish CI on this PR a fluke or something that needs fixing?

**Comment by adamewozniak** [comment]
Alternatively could we just remove terra from the docker build altogether? Afaik we don't need it for testnet anymore

**Comment by dreamcodez** [comment]
> Alternatively could we just remove terra from the docker build altogether? Afaik we don't need it for testnet anymore

this failure has nothing to do with terra.. some sort of permissions issue strange because nothing changed. could be a fluke. retrying build....

**Comment by dreamcodez** [comment]
> Is the failing image publish CI on this PR a fluke or something that needs fixing?

more info, will troubleshoot more tomorrow:

```
umee-node.docker.final (docker-push): denied: Permission "artifactregistry.repositories.uploadArtifacts" denied on resource "projects/umeedefi/locations/us/repositories/stack" (or it may not exist)
```

**Comment by dreamcodez** [comment]
Given how much the complexity of this has grown -- I don't think it really belongs in this repo anymore -- I need to refactor this in any case for our next testnet and I think its better if i move it to the infra repo.

**Comment by toteki** [comment]
I'm in favor of the move to infra - would like second opinion from other humans too though

**Review by adamewozniak — APPROVED** [review]
Agree - this stuff could be useful in another public repo, but this is not where it belongs

**Pull request merged**
