### PR TITLE
chore: WIP HAL-07 use the html/template package #1195

### PR DESCRIPTION
**Pull request by khoerling**
- when returning data back during an HTTP response
- since we can trust `json.Marshal`, let's just check the error case

## Description

closes: #XXXX

---

### Author Checklist

_All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues._

I have...

- [ ] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] added `!` to the type prefix if API or client breaking change
- [ ] added appropriate labels to the PR
- [ ] targeted the correct branch (see [PR Targeting](https://github.com/umee-network/umee/blob/main/CONTRIBUTING.md#pr-targeting))
- [ ] provided a link to the relevant issue or specification
- [ ] added a changelog entry to `CHANGELOG.md`
- [ ] included comments for [documenting Go code](https://blog.golang.org/godoc)
- [ ] updated the relevant documentation or specification
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed

### Reviewers Checklist

_All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items._

I have...

- [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed state machine logic
- [ ] reviewed API design and naming
- [ ] reviewed documentation is accurate
- [ ] reviewed tests and test coverage
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by khoerling** [comment]
Is there reason why we shouldn't trust `json.Marshal` to produce safe output?  Easy to add html/template there although it seems unnecessary after reading docs.

**Comment by adamewozniak** [comment]
> Is there reason why we shouldn't trust `json.Marshal` to produce safe output? Easy to add html/template there although it seems unnecessary after reading docs.

I think @RafilxTenfen might be able to give more context around here, iirc he was involved with the audit

**Comment by RafilxTenfen** [comment]
I think that Halborn was giving an suggestion to use [html/template](https://pkg.go.dev/html/template) and having templates for 
```go
                t := template.New("jsonMarshalError")
		t.Parse("<h1>Error {{.Code}}</h1> <a>{{.Error}}</a>")
		_ = t.Execute(w, bz)
```

also we could add HTML to the templates so they can look better... 

The "parse" part is not needed, but the idea is to avoid using `w.Write(bytes)`

**Review by RafilxTenfen — APPROVED** [review]
@adamewozniak Keith made a good point, that even that Halborn recommended to use `html/template` usually who is going to consume this API is like another API. So JSON is better in my opinion, what do you think?

**Comment by khoerling** [comment]
We could also inspect `Accept:` header and offer html or json, for human or computer

**Comment by adamewozniak** [comment]
> @adamewozniak Keith made a good point, that even that Halborn recommended to use `html/template` usually who is going to consume this API is like another API. So JSON is better in my opinion, what do you think?

I agree JSON works best here 👍

**Review by adamewozniak — APPROVED** [review]

**Pull request merged**
