### PR TITLE
build(deps): Update Cosmos SDK to 0.44 and Gravity Bridge to 0.2.0 (#73 and #76)

### LINKED ISSUE #73: Update SDK version to v0.44
Update SDK version to v0.44

----

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

### LINKED ISSUE #76: Update to latest gravity bridge
Update to latest Gravity Bridge release: https://github.com/PeggyJV/gravity-bridge/releases

- bump gravity version in go.mod
- bump gravity version in Dockerfile

To Test:

- Build docker image locally: `$ make docker-build-debug`
- Run e2e tests and ensure they pass: `$ go test -timeout 25m github.com/umee-network/umee/tests/e2e -v --count=1` or `$ make test-e2e`

----

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

### PR DESCRIPTION
**Pull request by toteki**
## Description

Update Cosmos SDK to 0.44 and Gravity Bridge to 0.2.0.

closes #73
closes #76

----

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

- [x] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] added `!` to the type prefix if API or client breaking change
- [x] targeted the correct branch (see [PR Targeting](https://github.com/umee-network/umee/blob/main/CONTRIBUTING.md#pr-targeting))
- [x] provided a link to the relevant issue or specification
- [ ] added a changelog entry to `CHANGELOG.md`
- [ ] included comments for [documenting Go code](https://blog.golang.org/godoc)
- [ ] updated the relevant documentation or specification
- [x] reviewed "Files changed" and left comments if necessary
- [x] confirmed all CI checks have passed

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

- [] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] confirmed `!` in the type prefix if API or client breaking change
- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed state machine logic
- [ ] reviewed API design and naming
- [ ] reviewed documentation is accurate
- [ ] reviewed tests and test coverage
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by toteki** [comment]
Note that Cosmos 0.44 removed a function x/auth/client.PrintUnsignedStdTx, which the previous version of Gravity (0.1.24) relied on.

Gravity 0.2.0 resolved this, among other things, which is why one of the Dependabot PRs failed CI tests (because it updated Cosmos without updating Gravity).

**Review by alexanderbez — APPROVED** [review]
Nice! I suppose the Gravity Bridge had no breaking changes!

**Comment by alexanderbez** [comment]
Feel free to merge this. Thanks @toteki

**Comment by toteki** [comment]
I may have to redo this branch / PR. I'm getting the following:

Merging is blocked
The base branch requires all commits to be signed.

I'll look into how to do this once I get home today.

**Comment by toteki** [comment]
Creating a new pull request with the fixed (signed) commit - I'm closing this one in the meantime

**Pull request closed without merging**
