### PR TITLE
chore: adr004 - use collateral utilization for interest rate calculation

### PR DESCRIPTION
**Pull request by robert-zaremba**
## Description
Follow up on #940

In #940 we update the borrow limit calculation. We should adjust the interest rate calculation accordingly.

Motivation: Borrow must have a well defined limit. Logical flow suggest to use that limit in interest rates calculation, rather than having 2 different limits.

---

### Author Checklist

_All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues._

I have...

- [x] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [x] added `!` to the type prefix if API or client breaking change
- [x] added appropriate labels to the PR
- [x] targeted the correct branch (see [PR Targeting](https://github.com/umee-network/umee/blob/main/CONTRIBUTING.md#pr-targeting))
- [x] provided a link to the relevant issue or specification
- [x] added a changelog entry to `CHANGELOG.md`
- [x] included comments for [documenting Go code](https://blog.golang.org/godoc)
- [x] updated the relevant documentation or specification
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed

### Reviewers Checklist

_All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items._

I have...

- [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed state machine logic
- [ ] reviewed API design and naming
- [ ] reviewed documentation is accurate
- [ ] reviewed tests and test coverage
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by toteki** [comment]
Suppose a `Token` exists with `CollateralWeight = 0.0` - it will never be used as collateral.

It is, however, fully functional for lending and borrowing.

In the current (`main` branch) system, the following interest rates apply:

| Supply | Borrowed | Interest Rate |
| - | - | - |
| 1000 | 0 | `BaseAPY` |
| 1000 | 200 | Something in between |
| 1000 | 1000 | `MaxAPY` |

The proposed system is incomplete, because it would result in

| Supply | Collateral | Borrowed | Interest Rate |
| - | - | - | - |
| 1000 | 0 | 0 | `BaseAPY` |
| 1000 | 0 | 200 | `BaseAPY` |
| 1000 | 0 | 1000 | `BaseAPY` |

In general, the existing system is meant to balance `TotalSupply` agains `TotalBorrowed` using market incentives, inspired by the Compound model. It does not primarily deal with collateral.

**Comment by robert-zaremba** [comment]
Idea will be to use both metrics and select the max. Our goal is to make sure the the market pays big fees if it's stretched. I will add more details to the ADR.

**Comment by toteki** [comment]
This PR can be closed, since the diff only contains the `supply_utilization -> collateral_utilization` switch.

We will either use both `supply_utilization` and collateral, or continue to only use `supply_utilization`.

**Comment by robert-zaremba** [comment]
Yes, I will need to redo it.

**Comment by robert-zaremba** [comment]
However I don't think we need another design doc.

**Pull request closed without merging**
