### PR TITLE
fix: switch to gb fork (facus hotfix for testnet)

### PR DESCRIPTION
**Pull request by dreamcodez**
## Description

Bring the gb testnet hotfix into main.

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

- [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] confirmed `!` in the type prefix if API or client breaking change
- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed state machine logic
- [ ] reviewed API design and naming
- [ ] reviewed documentation is accurate
- [ ] reviewed tests and test coverage
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by dreamcodez** [comment]
Open Questions:

1. Is the price-feeder update really necessary? (did we break interface?)

**Comment by adamewozniak** [comment]
> Open Questions:
> 
> 1. Is the price-feeder update really necessary? (did we break interface?)

It's an indirect dependency update, since it requires the `umee` package - so yeah the update is necessary

**Review by adamewozniak — APPROVED** [review]
👍 please make a task to switch this back once the fix is upstreamed @dreamcodez

**Review by adamewozniak — CHANGES_REQUESTED** [review]
Never mind, this was merged into GB :^) https://github.com/Gravity-Bridge/Gravity-Bridge/commit/8d660b559b0718c6ff4e20f3b355d94501d8dbb3

**Comment by dreamcodez** [comment]
I am closing this pr because of the fact that this fix is merged into upstream per @adamewozniak  :)

**Pull request closed without merging**
